name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@main

    - name: Configure Docker for Google Cloud Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and push Docker image to Google Artifact Registry
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/capstone-2/frontend:$GITHUB_SHA .
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/capstone-2/frontend:$GITHUB_SHA

    - name: Deploy to Cloud Run
      id: 'deploy'
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: 'frontend'
        region: 'us-central1'
        image: 'us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/capstone-2/frontend:${{ github.sha }}'
        flags: '--port=4173 --allow-unauthenticated'

    - name: Show frontend URL
      run: echo ${{ steps.deploy.outputs.url }}
